# DISABLED: Dependabot will fail in EWF repo
# Dependabot automatically creates pull requests for dependency updates
# This is disabled because it requires access to EWF repo settings and may fail
version: 2
# updates:
#   - package-ecosystem: "mix"
#     directory: "/"
#     open-pull-requests-limit: 20
#     schedule:
#       interval: "daily"
#
#   - package-ecosystem: "npm"
#     directory: "/apps/block_scout_web/assets"
#     open-pull-requests-limit: 10
#     schedule:
#       interval: "daily"
#
#   - package-ecosystem: "npm"
#     directory: "/apps/explorer"
#     open-pull-requests-limit: 10
#     schedule:
#       interval: "daily"
