name: Download GitHub Action Logs

on:
  workflow_dispatch:

jobs:
  logs-download:
    name: Download GH action logs
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.1

      - name: Download Logs
        uses: pawanbahuguna/action-logs@v2.0.0
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          ONLY_24: true
          LOGS_DIR: downloaded-logs

